#include "SpectrumEQComponent.h"
#include "Config/ColourPalette.h"
#include "Config/ParameterIDs.h"

namespace aurora
{
SpectrumEQComponent::SpectrumEQComponent(juce::AudioProcessorValueTreeState& s,AnalyzerFIFO& in,AnalyzerFIFO& out,std::function<double()> sr):state(s),inputAnalyzer(in),outputAnalyzer(out),sampleRate(std::move(sr)){setOpaque(true);setTooltip("Live input/output spectrum and draggable six-band equalizer. Drag horizontally for frequency, vertically for gain, and use the wheel for Q.");startTimerHz(30);}
juce::Rectangle<float> SpectrumEQComponent::plotBounds()const{return getLocalBounds().toFloat().reduced(1.0f).withTrimmedTop(36.0f).withTrimmedBottom(24.0f).withTrimmedLeft(42.0f).withTrimmedRight(14.0f);}
float SpectrumEQComponent::frequencyToX(float f)const{const auto plot=plotBounds();return juce::jmap(std::log10(juce::jlimit(20.0f,20000.0f,f)),std::log10(20.0f),std::log10(20000.0f),plot.getX(),plot.getRight());}
float SpectrumEQComponent::xToFrequency(float x)const{const auto plot=plotBounds();return std::pow(10.0f,juce::jmap(juce::jlimit(plot.getX(),plot.getRight(),x),plot.getX(),plot.getRight(),std::log10(20.0f),std::log10(20000.0f)));}
float SpectrumEQComponent::gainToY(float g)const{const auto plot=plotBounds();return juce::jmap(g,12.0f,-12.0f,plot.getY(),plot.getBottom());}float SpectrumEQComponent::yToGain(float y)const{const auto plot=plotBounds();return juce::jmap(juce::jlimit(plot.getY(),plot.getBottom(),y),plot.getY(),plot.getBottom(),12.0f,-12.0f);}
juce::Point<float> SpectrumEQComponent::nodePosition(int i)const{return{frequencyToX(state.getRawParameterValue(params::eqBandFrequency[static_cast<size_t>(i)])->load()),gainToY(state.getRawParameterValue(params::eqBandGain[static_cast<size_t>(i)])->load())};}
void SpectrumEQComponent::timerCallback(){if(state.getRawParameterValue(params::analyzerEnabled)->load()>0.5f&&state.getRawParameterValue(params::analyzerFreeze)->load()<0.5f){const auto s=state.getRawParameterValue(params::analyzerSmoothing)->load()*0.0098f;inputAnalyzer.update(s);outputAnalyzer.update(s);repaint();}}
void SpectrumEQComponent::paint(juce::Graphics& g)
{
    juce::ColourGradient gradient(colours::panelElevated,0.0f,0.0f,colours::panel,0.0f,static_cast<float>(getHeight()),false);g.setGradientFill(gradient);g.fillAll();const auto card=getLocalBounds().toFloat().reduced(1.0f);g.setColour(colours::border);g.drawRoundedRectangle(card,10.0f,1.0f);g.setColour(colours::text);g.setFont(juce::FontOptions(14.0f,juce::Font::bold));g.drawText("SPECTRUM + PARAMETRIC EQ",16,8,getWidth()-250,22,juce::Justification::centredLeft,true);g.setColour(colours::textSecondary);g.setFont(juce::FontOptions(11.0f));g.drawFittedText("Drag nodes: frequency / gain    Wheel: Q    Double-click: reset",juce::jmax(250,getWidth()/2),8,juce::jmax(1,getWidth()-juce::jmax(250,getWidth()/2)-16),22,juce::Justification::centredRight,1,0.75f);
    const auto plot=plotBounds();g.setColour(colours::background.withAlpha(0.42f));g.fillRoundedRectangle(plot,5.0f);const int frequencies[]{20,50,100,200,500,1000,2000,5000,10000,20000};for(auto frequency:frequencies){const auto x=frequencyToX(static_cast<float>(frequency));g.setColour(colours::grid);g.drawVerticalLine(static_cast<int>(x),plot.getY(),plot.getBottom());g.setColour(colours::textSecondary);g.setFont(juce::FontOptions(9.5f));const auto label=frequency>=1000?juce::String(frequency/1000)+"k":juce::String(frequency);g.drawText(label,static_cast<int>(x)-18,static_cast<int>(plot.getBottom())+3,36,16,juce::Justification::centred);}
    for(int db=-12;db<=12;db+=6){const auto y=gainToY(static_cast<float>(db));g.setColour(db==0?colours::border.brighter(0.12f):colours::grid);g.drawHorizontalLine(static_cast<int>(y),plot.getX(),plot.getRight());g.setColour(colours::textSecondary);g.setFont(juce::FontOptions(9.5f));g.drawText((db>0?"+":"")+juce::String(db)+" dB",2,static_cast<int>(y)-8,37,16,juce::Justification::centredRight);}
    if(state.getRawParameterValue(params::analyzerEnabled)->load()>0.5f){const int mode=static_cast<int>(state.getRawParameterValue(params::analyzerMode)->load());const auto drawSpectrum=[&](const auto& values,juce::Colour colour){juce::Path path;bool started=false;const auto sr=juce::jmax(1.0,sampleRate());for(int bin=1;bin<FFTAnalyzer::bins;++bin){const auto f=static_cast<float>(bin*sr/FFTAnalyzer::fftSize);if(f<20||f>20000)continue;const auto x=frequencyToX(f),y=juce::jmap(juce::jlimit(-90.0f,12.0f,values[static_cast<size_t>(bin)]),12.0f,-90.0f,plot.getY(),plot.getBottom());if(!started){path.startNewSubPath(x,y);started=true;}else path.lineTo(x,y);}g.setColour(colour);g.strokePath(path,juce::PathStrokeType(1.4f));};if(mode==0||mode==2)drawSpectrum(inputAnalyzer.magnitudes(),colours::muted);if(mode==1||mode==2)drawSpectrum(outputAnalyzer.magnitudes(),colours::cyan.withAlpha(0.75f));}
    juce::Path response;for(int x=static_cast<int>(plot.getX());x<=static_cast<int>(plot.getRight());x+=2){const auto f=xToFrequency(static_cast<float>(x));double db=0;for(int i=0;i<6;++i){if(state.getRawParameterValue(params::eqBandEnabled[i])->load()<0.5f)continue;const auto freq=state.getRawParameterValue(params::eqBandFrequency[i])->load(),gain=state.getRawParameterValue(params::eqBandGain[i])->load(),q=state.getRawParameterValue(params::eqBandQ[i])->load();using Coefficients=juce::dsp::IIR::Coefficients<float>;Coefficients::Ptr c;if(i==0)c=Coefficients::makeLowShelf(sampleRate(),freq,0.707f,juce::Decibels::decibelsToGain(gain));else if(i==5)c=Coefficients::makeHighShelf(sampleRate(),freq,0.707f,juce::Decibels::decibelsToGain(gain));else c=Coefficients::makePeakFilter(sampleRate(),freq,q,juce::Decibels::decibelsToGain(gain));db+=juce::Decibels::gainToDecibels(static_cast<float>(c->getMagnitudeForFrequency(f,sampleRate())));}const auto y=gainToY(juce::jlimit(-12.0f,12.0f,static_cast<float>(db)));if(x==static_cast<int>(plot.getX()))response.startNewSubPath(static_cast<float>(x),y);else response.lineTo(static_cast<float>(x),y);}g.setColour(colours::green);g.strokePath(response,juce::PathStrokeType(2.2f,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));
    for(int i=0;i<6;++i){auto p=nodePosition(i);g.setColour(colours::background.withAlpha(0.7f));g.fillEllipse(juce::Rectangle<float>(20,20).withCentre(p));g.setColour(i==selected?colours::amber:colours::cyan);g.fillEllipse(juce::Rectangle<float>(16,16).withCentre(p));g.setColour(colours::background);g.setFont(juce::FontOptions(10.0f,juce::Font::bold));g.drawText(juce::String(i+1),juce::Rectangle<int>(16,16).withCentre(p.toInt()),juce::Justification::centred);}
}
void SpectrumEQComponent::mouseDown(const juce::MouseEvent& e){float best=25;selected=-1;for(int i=0;i<6;++i){auto d=nodePosition(i).getDistanceFrom(e.position);if(d<best){best=d;selected=i;}}if(selected>=0){state.getParameter(params::eqBandFrequency[selected])->beginChangeGesture();state.getParameter(params::eqBandGain[selected])->beginChangeGesture();}}
void SpectrumEQComponent::setBandValue(const char* id,float value){if(auto* p=state.getParameter(id))p->setValueNotifyingHost(p->convertTo0to1(value));}
void SpectrumEQComponent::mouseDrag(const juce::MouseEvent& e){if(selected<0)return;setBandValue(params::eqBandFrequency[selected],xToFrequency(e.position.x));setBandValue(params::eqBandGain[selected],yToGain(e.position.y));repaint();}
void SpectrumEQComponent::mouseUp(const juce::MouseEvent&){if(selected>=0){state.getParameter(params::eqBandFrequency[selected])->endChangeGesture();state.getParameter(params::eqBandGain[selected])->endChangeGesture();}}
void SpectrumEQComponent::mouseDoubleClick(const juce::MouseEvent& e){mouseDown(e);if(selected>=0){auto* f=state.getParameter(params::eqBandFrequency[selected]);auto* gain=state.getParameter(params::eqBandGain[selected]);f->setValueNotifyingHost(f->getDefaultValue());gain->setValueNotifyingHost(gain->getDefaultValue());}}
void SpectrumEQComponent::mouseWheelMove(const juce::MouseEvent&,const juce::MouseWheelDetails& w){if(selected<0)return;auto* q=state.getParameter(params::eqBandQ[selected]);const auto actual=q->convertFrom0to1(q->getValue());setBandValue(params::eqBandQ[selected],actual+w.deltaY*0.5f);}
}
