#include "SpectrumEQComponent.h"
#include "Config/ColourPalette.h"
#include "Config/ParameterIDs.h"

namespace aurora
{
SpectrumEQComponent::SpectrumEQComponent(juce::AudioProcessorValueTreeState& s,AnalyzerFIFO& in,AnalyzerFIFO& out,std::function<double()> sr):state(s),inputAnalyzer(in),outputAnalyzer(out),sampleRate(std::move(sr)){setOpaque(true);setTooltip("Live input/output spectrum and draggable six-band equalizer. Drag horizontally for frequency, vertically for gain, and use the wheel for Q.");startTimerHz(30);}
float SpectrumEQComponent::frequencyToX(float f)const{return juce::jmap(std::log10(juce::jlimit(20.0f,20000.0f,f)),std::log10(20.0f),std::log10(20000.0f),0.0f,static_cast<float>(getWidth()));}
float SpectrumEQComponent::xToFrequency(float x)const{return std::pow(10.0f,juce::jmap(juce::jlimit(0.0f,static_cast<float>(getWidth()),x),0.0f,static_cast<float>(getWidth()),std::log10(20.0f),std::log10(20000.0f)));}
float SpectrumEQComponent::gainToY(float g)const{return juce::jmap(g,12.0f,-12.0f,0.0f,static_cast<float>(getHeight()));}float SpectrumEQComponent::yToGain(float y)const{return juce::jmap(juce::jlimit(0.0f,static_cast<float>(getHeight()),y),0.0f,static_cast<float>(getHeight()),12.0f,-12.0f);}
juce::Point<float> SpectrumEQComponent::nodePosition(int i)const{return{frequencyToX(state.getRawParameterValue(params::eqBandFrequency[static_cast<size_t>(i)])->load()),gainToY(state.getRawParameterValue(params::eqBandGain[static_cast<size_t>(i)])->load())};}
void SpectrumEQComponent::timerCallback(){if(state.getRawParameterValue(params::analyzerEnabled)->load()>0.5f&&state.getRawParameterValue(params::analyzerFreeze)->load()<0.5f){const auto s=state.getRawParameterValue(params::analyzerSmoothing)->load()*0.0098f;inputAnalyzer.update(s);outputAnalyzer.update(s);repaint();}}
void SpectrumEQComponent::paint(juce::Graphics& g)
{
    g.fillAll(colours::panel);g.setColour(colours::grid);for(auto f:{20,50,100,200,500,1000,2000,5000,10000,20000}){auto x=frequencyToX(static_cast<float>(f));g.drawVerticalLine(static_cast<int>(x),0.0f,static_cast<float>(getHeight()));}for(int db=-12;db<=12;db+=6)g.drawHorizontalLine(static_cast<int>(gainToY(static_cast<float>(db))),0,static_cast<float>(getWidth()));
    if(state.getRawParameterValue(params::analyzerEnabled)->load()>0.5f){const int mode=static_cast<int>(state.getRawParameterValue(params::analyzerMode)->load());const auto drawSpectrum=[&](const auto& values,juce::Colour colour){juce::Path path;bool started=false;const auto sr=juce::jmax(1.0,sampleRate());for(int bin=1;bin<FFTAnalyzer::bins;++bin){const auto f=static_cast<float>(bin*sr/FFTAnalyzer::fftSize);if(f<20||f>20000)continue;const auto x=frequencyToX(f),y=juce::jmap(juce::jlimit(-90.0f,12.0f,values[static_cast<size_t>(bin)]),12.0f,-90.0f,0.0f,static_cast<float>(getHeight()));if(!started){path.startNewSubPath(x,y);started=true;}else path.lineTo(x,y);}g.setColour(colour);g.strokePath(path,juce::PathStrokeType(1.4f));};if(mode==0||mode==2)drawSpectrum(inputAnalyzer.magnitudes(),colours::muted);if(mode==1||mode==2)drawSpectrum(outputAnalyzer.magnitudes(),colours::cyan.withAlpha(0.75f));}
    juce::Path response;for(int x=0;x<getWidth();x+=2){const auto f=xToFrequency(static_cast<float>(x));double db=0;for(int i=0;i<6;++i){if(state.getRawParameterValue(params::eqBandEnabled[i])->load()<0.5f)continue;const auto freq=state.getRawParameterValue(params::eqBandFrequency[i])->load(),gain=state.getRawParameterValue(params::eqBandGain[i])->load(),q=state.getRawParameterValue(params::eqBandQ[i])->load();juce::IIRCoefficients c=i==0?juce::IIRCoefficients::makeLowShelf(sampleRate(),freq,0.707f,juce::Decibels::decibelsToGain(gain)):i==5?juce::IIRCoefficients::makeHighShelf(sampleRate(),freq,0.707f,juce::Decibels::decibelsToGain(gain)):juce::IIRCoefficients::makePeakFilter(sampleRate(),freq,q,juce::Decibels::decibelsToGain(gain));db+=juce::Decibels::gainToDecibels(static_cast<float>(c.getMagnitudeForFrequency(f,sampleRate())));}const auto y=gainToY(juce::jlimit(-12.0f,12.0f,static_cast<float>(db)));if(x==0)response.startNewSubPath(0,y);else response.lineTo(static_cast<float>(x),y);}g.setColour(colours::green);g.strokePath(response,juce::PathStrokeType(2));
    for(int i=0;i<6;++i){auto p=nodePosition(i);g.setColour(i==selected?colours::amber:colours::cyan);g.fillEllipse(juce::Rectangle<float>(12,12).withCentre(p));g.setColour(colours::background);g.drawText(juce::String(i+1),juce::Rectangle<int>(12,12).withCentre(p.toInt()),juce::Justification::centred);}
}
void SpectrumEQComponent::mouseDown(const juce::MouseEvent& e){float best=25;selected=-1;for(int i=0;i<6;++i){auto d=nodePosition(i).getDistanceFrom(e.position);if(d<best){best=d;selected=i;}}if(selected>=0){state.getParameter(params::eqBandFrequency[selected])->beginChangeGesture();state.getParameter(params::eqBandGain[selected])->beginChangeGesture();}}
void SpectrumEQComponent::setBandValue(int band,const char* id,float value){if(auto* p=state.getParameter(id))p->setValueNotifyingHost(p->convertTo0to1(value));}
void SpectrumEQComponent::mouseDrag(const juce::MouseEvent& e){if(selected<0)return;setBandValue(selected,params::eqBandFrequency[selected],xToFrequency(e.position.x));setBandValue(selected,params::eqBandGain[selected],yToGain(e.position.y));repaint();}
void SpectrumEQComponent::mouseUp(const juce::MouseEvent&){if(selected>=0){state.getParameter(params::eqBandFrequency[selected])->endChangeGesture();state.getParameter(params::eqBandGain[selected])->endChangeGesture();}}
void SpectrumEQComponent::mouseDoubleClick(const juce::MouseEvent& e){mouseDown(e);if(selected>=0){auto* f=state.getParameter(params::eqBandFrequency[selected]);auto* gain=state.getParameter(params::eqBandGain[selected]);f->setValueNotifyingHost(f->getDefaultValue());gain->setValueNotifyingHost(gain->getDefaultValue());}}
void SpectrumEQComponent::mouseWheelMove(const juce::MouseEvent&,const juce::MouseWheelDetails& w){if(selected<0)return;auto* q=state.getParameter(params::eqBandQ[selected]);const auto actual=q->convertFrom0to1(q->getValue());setBandValue(selected,params::eqBandQ[selected],actual+w.deltaY*0.5f);}
}
