[CmdletBinding()]
param([Parameter(Mandatory)][string]$Version,[string]$ValidationStatus='VALIDATION NOT RUN - VALIDATOR UNAVAILABLE',[string]$InstallerStatus='NOT BUILT',[string]$TestResult='UNKNOWN')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$dist=Join-Path $root 'dist';if($Version-notmatch'^\d+\.\d+\.\d+$'){throw 'Version must be semantic x.y.z'}
$files=Get-ChildItem -LiteralPath $dist -File|Where-Object{$_.Name-notmatch'Checksums|ReleaseManifest|TestResults|macOS'-and$_.Name-match"-v$([regex]::Escape($Version))\."}|Sort-Object Name
$outputs=@($files|ForEach-Object{[ordered]@{file=$_.Name;sizeBytes=$_.Length;sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}})
$gitSha=if($env:GITHUB_SHA){$env:GITHUB_SHA}else{git -C $root rev-parse HEAD 2>$null;if($LASTEXITCODE-ne 0){'UNCOMMITTED'}}
$gitTag=if($env:GITHUB_REF_TYPE-eq'tag'){$env:GITHUB_REF_NAME}else{'NONE'}
$cmakeVersion=try{(& cmake --version|Select-Object -First 1)-replace'^cmake version\s+',''}catch{'UNAVAILABLE'}
$manifest=[ordered]@{schemaVersion=1;productName='Aurora Broadcast Processor';productVersion=$Version;companyName='Ammar Audio Labs';gitCommit="$gitSha".Trim();gitTag=$gitTag;workflowRunId=if($env:GITHUB_RUN_ID){$env:GITHUB_RUN_ID}else{'LOCAL'};workflowRunNumber=if($env:GITHUB_RUN_NUMBER){$env:GITHUB_RUN_NUMBER}else{'LOCAL'};buildTimestampUtc=[DateTime]::UtcNow.ToString('o');runnerOperatingSystem=if($env:RUNNER_OS){$env:RUNNER_OS}else{'Windows'};runnerImage=if($env:ImageOS){$env:ImageOS}else{'LOCAL'};cmakeVersion=$cmakeVersion;compilerVersion=if($env:VCToolsVersion){$env:VCToolsVersion}else{'UNAVAILABLE'};juceVersion='8.0.14';juceCommit='2cdfca8feb300fb424002ba2c2751569e5bacb64';buildConfiguration='Release';architecture='x64';pluginFormats=@('VST3','Standalone');testsExecuted=@('parameter','state','preset','DSP','crossover','stereo','limiter','lifecycle','stress');testResult=$TestResult;validationStatus=$ValidationStatus;installerStatus=$InstallerStatus;codeSigningStatus='UNSIGNED';repeatability='Repeatable clean CI build';outputs=$outputs}
$path=Join-Path $dist "AuroraBroadcastProcessor-ReleaseManifest-v$Version.json";$manifest|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $path -Encoding UTF8;Get-Content -Raw $path|ConvertFrom-Json|Out-Null;Write-Host "Wrote $path"
