[CmdletBinding()]param([string]$Version,[switch]$RequireInstaller,[ValidateSet('PASSED','FAILED','UNKNOWN')][string]$TestResult='UNKNOWN')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;if(-not$Version){$Version=(Get-Content -Raw (Join-Path $root 'VERSION.txt')).Trim()};if($Version-notmatch'^\d+\.\d+\.\d+$'){throw 'Version must be semantic x.y.z'};if((Get-Content -Raw (Join-Path $root 'VERSION.txt')).Trim()-ne$Version){throw 'Requested version differs from VERSION.txt'}
$dist=Join-Path $root 'dist';$stage=Join-Path $dist 'staging';if(Test-Path $stage){$resolved=[IO.Path]::GetFullPath($stage);$allowed=[IO.Path]::GetFullPath($dist);if(-not$resolved.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase)){throw 'Unsafe staging path'};Remove-Item -LiteralPath $resolved -Recurse -Force};New-Item -ItemType Directory -Path $stage -Force|Out-Null
$artefacts=Join-Path $root 'build/windows-x64/AuroraBroadcastProcessor_artefacts/Release';$vst3=Join-Path $artefacts 'VST3/Aurora Broadcast Processor.vst3';$standalone=Join-Path $artefacts 'Standalone/Aurora Broadcast Processor.exe';if(-not(Test-Path $vst3)){throw "VST3 missing: $vst3"};if(-not(Test-Path $standalone)){throw "Standalone missing: $standalone"}
function Copy-Common($target){New-Item -ItemType Directory -Path $target -Force|Out-Null;Copy-Item (Join-Path $root 'LICENSE_NOTICE.md'),(Join-Path $root 'THIRD_PARTY_NOTICES.md'),(Join-Path $root 'VERSION.txt') -Destination $target;}
$combined=Join-Path $stage 'combined';Copy-Common $combined;New-Item -ItemType Directory -Path (Join-Path $combined 'VST3'),(Join-Path $combined 'Standalone'),(Join-Path $combined 'Documentation')-Force|Out-Null;Copy-Item $vst3 (Join-Path $combined 'VST3')-Recurse;Copy-Item $standalone (Join-Path $combined 'Standalone');Copy-Item (Join-Path $root 'README.md') (Join-Path $combined 'Documentation/README.md');foreach($d in @('INSTALLATION.md','HOST_TESTING.md','PRESETS.md','KNOWN_LIMITATIONS.md')){Copy-Item (Join-Path $root "docs/$d") (Join-Path $combined "Documentation/$d")}
$buildInfo=[ordered]@{product='Aurora Broadcast Processor';version=$Version;juce='8.0.14';configuration='Release';architecture='x64';formats=@('VST3','Standalone');codeSigning='UNSIGNED';timestampUtc=[DateTime]::UtcNow.ToString('o')};$buildInfo|ConvertTo-Json|Set-Content (Join-Path $combined 'BUILD_INFO.json') -Encoding UTF8
$vstage=Join-Path $stage 'vst3';Copy-Common $vstage;Copy-Item $vst3 $vstage -Recurse;Copy-Item (Join-Path $root 'docs/INSTALLATION.md') $vstage
$sstage=Join-Path $stage 'standalone';Copy-Common $sstage;Copy-Item $standalone $sstage;Copy-Item (Join-Path $root 'docs/INSTALLATION.md') $sstage
Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem
function New-DeterministicZip([string]$source,[string]$destination){if(Test-Path $destination){Remove-Item -LiteralPath $destination -Force};$stream=[IO.File]::Open($destination,[IO.FileMode]::CreateNew);try{$zip=[IO.Compression.ZipArchive]::new($stream,[IO.Compression.ZipArchiveMode]::Create,$false);try{Get-ChildItem -LiteralPath $source -File -Recurse|Sort-Object{$_.FullName.Substring($source.Length)}|ForEach-Object{$name=$_.FullName.Substring($source.Length).TrimStart([char[]]@('\','/'))-replace'\\','/';$entry=$zip.CreateEntry($name,[IO.Compression.CompressionLevel]::Optimal);$entry.LastWriteTime=[DateTimeOffset]::new(1980,1,1,0,0,0,[TimeSpan]::Zero);$input=$_.OpenRead();$output=$entry.Open();try{$input.CopyTo($output)}finally{$output.Dispose();$input.Dispose()}}}finally{$zip.Dispose()}}finally{$stream.Dispose()}}
New-DeterministicZip $combined (Join-Path $dist "AuroraBroadcastProcessor-Windows-x64-v$Version.zip");New-DeterministicZip $vstage (Join-Path $dist "AuroraBroadcastProcessor-VST3-v$Version.zip");New-DeterministicZip $sstage (Join-Path $dist "AuroraBroadcastProcessor-Standalone-v$Version.zip")
$testStage=Join-Path $stage 'tests';New-Item -ItemType Directory $testStage -Force|Out-Null;Copy-Item (Join-Path $root 'docs/BUILD_LOG.md'),(Join-Path $root 'docs/vst3-validation.txt') -Destination $testStage -ErrorAction SilentlyContinue;New-DeterministicZip $testStage (Join-Path $dist "AuroraBroadcastProcessor-TestResults-v$Version.zip")
$installerStatus='NOT BUILT';$iscc=(Get-Command iscc.exe -ErrorAction SilentlyContinue).Source;if($iscc){&$iscc "/DMyAppVersion=$Version" "/DSourceRoot=$root" "/DOutputDir=$dist" (Join-Path $root 'installer/AuroraBroadcastProcessor.iss');if($LASTEXITCODE-ne 0){throw 'Inno Setup failed'};$installerStatus='BUILT - UNSIGNED'}elseif($RequireInstaller){throw 'Inno Setup compiler is required but unavailable'}
$validationText=if(Test-Path(Join-Path $root 'docs/vst3-validation.txt')){Get-Content -Raw (Join-Path $root 'docs/vst3-validation.txt')}else{'VALIDATION NOT RUN - VALIDATOR UNAVAILABLE'};$validationStatus=if($validationText-match'VALIDATION PASSED'){'PASSED'}elseif($validationText-match'VALIDATION NOT RUN'){'VALIDATION NOT RUN - VALIDATOR UNAVAILABLE'}else{'FAILED OR UNKNOWN'}
& (Join-Path $PSScriptRoot 'generate-release-manifest.ps1') -Version $Version -InstallerStatus $installerStatus -TestResult $TestResult -ValidationStatus $validationStatus;& (Join-Path $PSScriptRoot 'calculate-checksums.ps1') -Version $Version;& (Join-Path $PSScriptRoot 'verify-release-output.ps1') -Version $Version -RequireInstaller:$RequireInstaller
