[CmdletBinding()]param([string]$Version,[switch]$RequireInstaller,[switch]$BuildOnly)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;if(-not$Version){$Version=(Get-Content -Raw (Join-Path $root 'VERSION.txt')).Trim()};$dist=Join-Path $root 'dist';$artefacts=Join-Path $root 'build/windows-x64/AuroraBroadcastProcessor_artefacts/Release';$vst3=Join-Path $artefacts 'VST3/Aurora Broadcast Processor.vst3';$exe=Join-Path $artefacts 'Standalone/Aurora Broadcast Processor.exe'
foreach($p in @($vst3,$exe)){if(-not(Test-Path $p)){throw "Required build output missing: $p"}};$binary=Get-ChildItem $vst3 -Recurse -File|Where-Object{$_.Extension-eq'.vst3'}|Select-Object -First 1;if(-not$binary-or$binary.Length-eq 0){throw 'VST3 bundle binary missing or empty'};if((Get-Item $exe).Length-eq 0){throw 'Standalone is empty'};if($BuildOnly){Write-Host 'Build output verification passed.';exit 0}
$names=@("AuroraBroadcastProcessor-Windows-x64-v$Version.zip","AuroraBroadcastProcessor-VST3-v$Version.zip","AuroraBroadcastProcessor-Standalone-v$Version.zip","AuroraBroadcastProcessor-TestResults-v$Version.zip","AuroraBroadcastProcessor-ReleaseManifest-v$Version.json","AuroraBroadcastProcessor-Checksums-v$Version.txt");$setupName="AuroraBroadcastProcessor-Setup-v$Version.exe";if($RequireInstaller-or(Test-Path(Join-Path $dist $setupName))){$names+=$setupName};foreach($n in $names){$p=Join-Path $dist $n;if(-not(Test-Path $p)-or(Get-Item $p).Length-eq 0){throw "Missing or empty release file: $n"}}
Add-Type -AssemblyName System.IO.Compression.FileSystem;foreach($n in $names|Where-Object{$_-like'*.zip'}){$zip=[IO.Compression.ZipFile]::OpenRead((Join-Path $dist $n));try{$entries=@($zip.Entries.FullName);if($entries-match'(^|/)(prompt\.txt|\.git|\.github|CMakeCache\.txt|Debug)($|/)'-or$entries-match'\.(pfx|p12|pem|key|cer|crt|obj|pdb|ilk|exp|lib)$'){throw "Prohibited content in $n"}}finally{$zip.Dispose()}}
$combined=[IO.Compression.ZipFile]::OpenRead((Join-Path $dist "AuroraBroadcastProcessor-Windows-x64-v$Version.zip"));try{$required=@('Standalone/Aurora Broadcast Processor.exe','Documentation/README.md','Documentation/INSTALLATION.md','Documentation/HOST_TESTING.md','Documentation/PRESETS.md','Documentation/KNOWN_LIMITATIONS.md','LICENSE_NOTICE.md','THIRD_PARTY_NOTICES.md','VERSION.txt','BUILD_INFO.json');foreach($r in $required){if($combined.Entries.FullName-notcontains$r){throw "Combined ZIP missing $r"}};if(-not($combined.Entries.FullName|Where-Object{$_-like'VST3/Aurora Broadcast Processor.vst3/*'})){throw 'Combined ZIP has no VST3 content'};$versionEntry=$combined.GetEntry('VERSION.txt');$reader=[IO.StreamReader]::new($versionEntry.Open());try{$archiveVersion=$reader.ReadToEnd().Trim()}finally{$reader.Dispose()};if($archiveVersion-ne$Version){throw 'Combined ZIP VERSION.txt mismatch'};$infoEntry=$combined.GetEntry('BUILD_INFO.json');$reader=[IO.StreamReader]::new($infoEntry.Open());try{$info=$reader.ReadToEnd()|ConvertFrom-Json}finally{$reader.Dispose()};if($info.version-ne$Version-or$info.juce-ne'8.0.14'){throw 'Combined ZIP BUILD_INFO.json mismatch'}}finally{$combined.Dispose()}
$manifest=Get-Content -Raw (Join-Path $dist "AuroraBroadcastProcessor-ReleaseManifest-v$Version.json")|ConvertFrom-Json;if($manifest.productVersion-ne$Version-or$manifest.juceVersion-ne'8.0.14'){throw 'Manifest version mismatch'}
$checksumPath=Join-Path $dist "AuroraBroadcastProcessor-Checksums-v$Version.txt";$covered=@();foreach($line in Get-Content $checksumPath){if($line-notmatch'^([0-9a-f]{64})  (.+)$'){throw 'Invalid checksum line'};$covered+=$Matches[2];$actual=(Get-FileHash (Join-Path $dist $Matches[2]) -Algorithm SHA256).Hash.ToLowerInvariant();if($actual-ne$Matches[1]){throw "Checksum mismatch: $($Matches[2])"}};$expectedChecksums=Get-ChildItem $dist -File|Where-Object{$_.Name-ne[IO.Path]::GetFileName($checksumPath)-and$_.Name-match"-v$([regex]::Escape($Version))\.(zip|exe|json)$"};foreach($asset in $expectedChecksums){if($covered-notcontains$asset.Name){throw "Checksum coverage missing: $($asset.Name)"}}
$textFiles=Get-ChildItem (Join-Path $dist 'staging') -Recurse -File -Include *.md,*.txt,*.json -ErrorAction SilentlyContinue;foreach($f in $textFiles){$text=Get-Content -Raw $f.FullName;if($text-match'[A-Za-z]:\\Users\\'){throw "Local user path found in $($f.Name)"};if($text-match'BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY'){throw "Private key found in $($f.Name)"}}
Write-Host 'Release output verification passed.'
