#include "PluginEditor.h"
#include "Config/ColourPalette.h"
#include "Config/ParameterIDs.h"
#include "Config/ProductConfig.h"

namespace aurora
{
KnobControl::KnobControl(juce::AudioProcessorValueTreeState& s,const char* id,const juce::String& name,const juce::String& tip){label.setText(name,juce::dontSendNotification);label.setJustificationType(juce::Justification::centred);slider.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);slider.setTextBoxStyle(juce::Slider::TextBoxBelow,false,86,20);slider.setDoubleClickReturnValue(true,dynamic_cast<juce::RangedAudioParameter*>(s.getParameter(id))->convertFrom0to1(s.getParameter(id)->getDefaultValue()));slider.setTooltip(tip);slider.setName(name);addAndMakeVisible(label);addAndMakeVisible(slider);attachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(s,id,slider);}
void KnobControl::resized(){auto r=getLocalBounds();label.setBounds(r.removeFromTop(20));slider.setBounds(r);}
ToggleControl::ToggleControl(juce::AudioProcessorValueTreeState& s,const char* id,const juce::String& name,const juce::String& tip){button.setButtonText(name);button.setTooltip(tip);button.setName(name);addAndMakeVisible(button);attachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(s,id,button);}void ToggleControl::resized(){button.setBounds(getLocalBounds());}
ChoiceControl::ChoiceControl(juce::AudioProcessorValueTreeState& s,const char* id,const juce::String& name,juce::StringArray items){label.setText(name,juce::dontSendNotification);label.setJustificationType(juce::Justification::centred);box.addItemList(items,1);addAndMakeVisible(label);addAndMakeVisible(box);attachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(s,id,box);}void ChoiceControl::resized(){auto r=getLocalBounds();label.setBounds(r.removeFromTop(18));box.setBounds(r.reduced(3));}
MeterDisplay::MeterDisplay(MeteringEngine& m):meters(m){setTooltip("Actual input/output levels and dynamics gain reduction.");}
void MeterDisplay::mouseDown(const juce::MouseEvent&){meters.clipWarning.store(false);meters.oversampledPeakWarning.store(false);repaint();}
void MeterDisplay::paint(juce::Graphics& g){g.fillAll(colours::panel);const auto draw=[&](float value,float rmsValue,juce::Rectangle<float> r,juce::Colour c){g.setColour(colours::grid);g.fillRoundedRectangle(r,2);const auto norm=[&](float v){return juce::jlimit(0.0f,1.0f,juce::jmap(juce::Decibels::gainToDecibels(v,-60.0f),-60.0f,0.0f,0.0f,1.0f));};g.setColour(c.darker(0.45f));g.fillRoundedRectangle(r.withTop(r.getBottom()-r.getHeight()*norm(rmsValue)),2);g.setColour(c);const auto peakY=r.getBottom()-r.getHeight()*norm(value);g.fillRect(r.getX(),peakY,r.getWidth(),2.0f);};auto r=getLocalBounds().toFloat().reduced(8);const auto w=12.0f;draw(meters.inputPeak[0].load(),meters.inputRms[0].load(),r.removeFromLeft(w),colours::green);r.removeFromLeft(4);draw(meters.inputPeak[1].load(),meters.inputRms[1].load(),r.removeFromLeft(w),colours::green);r.removeFromLeft(12);draw(meters.outputPeak[0].load(),meters.outputRms[0].load(),r.removeFromLeft(w),colours::cyan);r.removeFromLeft(4);draw(meters.outputPeak[1].load(),meters.outputRms[1].load(),r.removeFromLeft(w),colours::cyan);g.setColour(meters.clipWarning.load()?colours::red:colours::textSecondary);g.setFont(10);juce::String bands="B";for(int i=0;i<4;++i)bands<<i+1<<":"<<juce::String(meters.bandReductionDb[i].load(),1)<<" ";g.drawFittedText("IN       OUT\nAGC "+juce::String(meters.agcGainDb.load(),1)+" dB\n"+bands+"\nLIM -"+juce::String(meters.limiterReductionDb.load(),1)+" dB  COR "+juce::String(meters.correlation.load(),2),getLocalBounds().reduced(4),juce::Justification::bottomLeft,5);}

AuroraBroadcastProcessorEditor::AuroraBroadcastProcessorEditor(AuroraBroadcastProcessor& p):AudioProcessorEditor(p),processor(p),spectrum(p.parameters,p.engine().inputAnalyzer(),p.engine().outputAnalyzer(),[this]{return processor.getSampleRate();}),meterDisplay(p.engine().meters())
{
    processor.engine().setAnalyzerConsumerActive(true);setLookAndFeel(&lookAndFeel);setOpaque(true);setResizable(true,true);setResizeLimits(config::minimumWidth,config::minimumHeight,config::maximumWidth,config::maximumHeight);auto state=p.parameters.state;setSize(static_cast<int>(state.getProperty("editorWidth",config::defaultWidth)),static_cast<int>(state.getProperty("editorHeight",config::defaultHeight)));
    title.setText(juce::String(config::productName).toUpperCase(),juce::dontSendNotification);title.setFont(juce::FontOptions(20,juce::Font::bold));title.setColour(juce::Label::textColourId,colours::cyan);presetLabel.setText("PRESET",juce::dontSendNotification);for(const auto& preset:factoryPresets())presetBox.addItem(preset.name,presetBox.getNumItems()+1);presetBox.setSelectedItemIndex(p.presets.currentFactoryIndex(),juce::dontSendNotification);
    advancedMode=static_cast<bool>(state.getProperty("advancedView",true));for(auto* c:{static_cast<juce::Component*>(&title),&presetLabel,&presetBox,&previous,&next,&save,&saveAs,&aButton,&bButton,&aToB,&bToA,&reset,&advanced,&info,&bypass,&spectrum,&meterDisplay,&viewport,&footer})addAndMakeVisible(c);viewport.setViewedComponent(&controlContent,false);viewport.setScrollBarsShown(true,false);viewport.setVisible(advancedMode);advanced.setToggleState(advancedMode,juce::dontSendNotification);bypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.parameters,params::globalBypass,bypass);
    presetBox.onChange=[this]{if(presetBox.getSelectedItemIndex()>=0)processor.presets.loadFactory(presetBox.getSelectedItemIndex());};previous.onClick=[this]{selectRelativePreset(-1);};next.onClick=[this]{selectRelativePreset(1);};save.onClick=[this]{savePreset();};saveAs.onClick=[this]{saveAsPreset();};aButton.onClick=[this]{processor.presets.selectA();aButton.setToggleState(true,juce::dontSendNotification);bButton.setToggleState(false,juce::dontSendNotification);};bButton.onClick=[this]{processor.presets.selectB();bButton.setToggleState(true,juce::dontSendNotification);aButton.setToggleState(false,juce::dontSendNotification);};aToB.onClick=[this]{processor.presets.copyAToB();};bToA.onClick=[this]{processor.presets.copyBToA();};reset.onClick=[this]{processor.presets.loadFactory(0);presetBox.setSelectedItemIndex(0,juce::dontSendNotification);};advanced.onClick=[this]{advancedMode=!advancedMode;advanced.setToggleState(advancedMode,juce::dontSendNotification);viewport.setVisible(advancedMode);processor.parameters.state.setProperty("advancedView",advancedMode,nullptr);resized();};info.onClick=[] {juce::AlertWindow::showMessageBoxAsync(juce::MessageBoxIconType::InfoIcon,config::productName,"Digital/internet broadcast processing. Not RF equipment or a certified compliance processor.\nVersion "+juce::String(config::version));};aButton.setToggleState(true,juce::dontSendNotification);
    addKnob(params::inputTrimDb,"Input","Input level before processing.");addKnob(params::highPassFrequencyHz,"HPF","High-pass cutoff.");addKnob(params::agcTargetDb,"AGC Target","Slow RMS level target.");addKnob(params::agcMaxGainDb,"AGC Gain","Maximum upward correction.");addKnob(params::agcMaxAttenuationDb,"AGC Atten","Maximum downward correction.");addKnob(params::agcAttackMs,"AGC Attack","Downward gain response time.");addKnob(params::agcReleaseMs,"AGC Release","Upward gain response time.");addKnob(params::agcGateThresholdDb,"AGC Gate","Stops silence from being raised.");
    addKnob(params::crossover1Hz,"X-Over 1","Low crossover.");addKnob(params::crossover2Hz,"X-Over 2","Mid crossover.");addKnob(params::crossover3Hz,"X-Over 3","High crossover.");addKnob(params::multibandAmountPercent,"MB Amount","Overall compression intensity.");
    for(int b=0;b<4;++b){const auto n=juce::String(b+1);addKnob(params::bandThreshold[b],"B"+n+" Threshold","Band compressor threshold.");addKnob(params::bandRatio[b],"B"+n+" Ratio","Band compression ratio.");addKnob(params::bandAttack[b],"B"+n+" Attack","Band attack time.");addKnob(params::bandRelease[b],"B"+n+" Release","Band release time.");addKnob(params::bandKnee[b],"B"+n+" Knee","Band soft-knee width.");addKnob(params::bandMakeup[b],"B"+n+" Makeup","Band makeup gain.");addKnob(params::bandMix[b],"B"+n+" Mix","Band parallel mix.");}
    addKnob(params::enhancerDriveDb,"Enh Drive","Harmonic density drive.");addKnob(params::enhancerMixPercent,"Enh Mix","Harmonic wet/dry mix.");addKnob(params::enhancerTonePercent,"Enh Tone","Harmonic brightness balance.");addKnob(params::stereoWidthPercent,"Width","Mid/side stereo width.");addKnob(params::stereoBalancePercent,"Balance","Stereo balance.");addKnob(params::monoBassFrequencyHz,"Mono Bass","Frequency below which side bass is reduced.");addKnob(params::clipperDriveDb,"Peak Drive","4x oversampled soft clipping drive.");addKnob(params::limiterDriveDb,"Limit Drive","Look-ahead limiter input drive.");addKnob(params::limiterCeilingDb,"Ceiling","Final sample ceiling.");addKnob(params::limiterLookaheadMs,"Lookahead","Limiter anticipation window.");addKnob(params::limiterReleaseMs,"Limit Release","Limiter recovery time.");addKnob(params::outputTrimDb,"Output","Final output trim.");addKnob(params::analyzerSmoothing,"FFT Smooth","Spectrum visual smoothing only.");
    addToggle(params::dcBlockEnabled,"DC Block","Remove sub-audible DC.");addToggle(params::highPassEnabled,"High Pass","Enable the input high-pass filter.");addToggle(params::agcEnabled,"AGC","Enable slow automatic gain control.");addToggle(params::eqEnabled,"EQ","Enable all EQ bands.");for(int i=0;i<6;++i)addToggle(params::eqBandEnabled[i],"EQ "+juce::String(i+1),"Enable this EQ band.");addToggle(params::multibandEnabled,"Multiband","Enable crossover compression.");for(int i=0;i<4;++i){addToggle(params::bandEnabled[i],"Band "+juce::String(i+1),"Enable this compressor band.");addToggle(params::bandSolo[i],"Solo "+juce::String(i+1),"Audition only this band.");}addToggle(params::enhancerEnabled,"Enhancer","Enable harmonic enhancement.");addToggle(params::stereoEnabled,"Stereo","Enable width and balance.");addToggle(params::monoBassEnabled,"Mono Bass","Reduce low-frequency side energy.");addToggle(params::correlationProtectionEnabled,"Correlation Guard","Reduce widening during negative correlation.");addToggle(params::clipperEnabled,"Oversampled Peak","Enable 4x oversampled soft clipping.");addToggle(params::limiterEnabled,"Limiter","Enable look-ahead limiting.");addToggle(params::invertLeft,"Invert L","Invert left polarity.");addToggle(params::invertRight,"Invert R","Invert right polarity.");addToggle(params::analyzerEnabled,"Analyzer","Enable real spectrum updates.");addToggle(params::analyzerFreeze,"Freeze","Freeze the spectrum display.");
    addChoice(params::clipperMode,"Peak Style",{"Soft","Firm"});addChoice(params::limiterStyle,"Limit Style",{"Transparent","Punch"});addChoice(params::analyzerMode,"Spectrum",{"Input","Output","Both"});startTimerHz(20);
}
AuroraBroadcastProcessorEditor::~AuroraBroadcastProcessorEditor(){processor.engine().setAnalyzerConsumerActive(false);processor.parameters.state.setProperty("editorWidth",getWidth(),nullptr);processor.parameters.state.setProperty("editorHeight",getHeight(),nullptr);setLookAndFeel(nullptr);}
void AuroraBroadcastProcessorEditor::addKnob(const char* id,const juce::String& n,const juce::String& t){auto c=std::make_unique<KnobControl>(processor.parameters,id,n,t);controlContent.addAndMakeVisible(*c);knobs.push_back(std::move(c));}void AuroraBroadcastProcessorEditor::addToggle(const char* id,const juce::String& n,const juce::String& t){auto c=std::make_unique<ToggleControl>(processor.parameters,id,n,t);controlContent.addAndMakeVisible(*c);toggles.push_back(std::move(c));}void AuroraBroadcastProcessorEditor::addChoice(const char* id,const juce::String& n,juce::StringArray a){auto c=std::make_unique<ChoiceControl>(processor.parameters,id,n,a);controlContent.addAndMakeVisible(*c);choices.push_back(std::move(c));}
void AuroraBroadcastProcessorEditor::paint(juce::Graphics& g){g.fillAll(colours::background);g.setColour(colours::grid);g.drawHorizontalLine(48,0,static_cast<float>(getWidth()));}
void AuroraBroadcastProcessorEditor::resized(){processor.parameters.state.setProperty("editorWidth",getWidth(),nullptr);processor.parameters.state.setProperty("editorHeight",getHeight(),nullptr);auto area=getLocalBounds().reduced(8);auto header=area.removeFromTop(40);title.setBounds(header.removeFromLeft(215));presetLabel.setBounds(header.removeFromLeft(40));previous.setBounds(header.removeFromLeft(24).reduced(2));next.setBounds(header.removeFromLeft(24).reduced(2));presetBox.setBounds(header.removeFromLeft(140).reduced(2));for(auto* b:{&save,&saveAs,&aButton,&bButton,&aToB,&bToA,&reset})b->setBounds(header.removeFromLeft(b==&saveAs?54:(b==&aButton||b==&bButton?30:44)).reduced(2));info.setBounds(header.removeFromRight(30).reduced(2));bypass.setBounds(header.removeFromRight(64));advanced.setBounds(header.removeFromRight(68).reduced(2));auto footerArea=area.removeFromBottom(24);footer.setBounds(footerArea);auto upper=advancedMode?area.removeFromTop(juce::jmax(220,static_cast<int>(area.getHeight()*0.52f))):area;meterDisplay.setBounds(upper.removeFromRight(100).reduced(4));spectrum.setBounds(upper.reduced(4));viewport.setBounds(area.reduced(0,4));const int cols=juce::jmax(6,getWidth()/112),cellW=110,knobH=104;int index=0;for(auto& k:knobs){const int row=index/cols,col=index%cols;k->setBounds(col*cellW,row*knobH,cellW,knobH);++index;}int y=((index+cols-1)/cols)*knobH+6;for(auto& t:toggles){const int col=(index++)%cols;if(col==0&&index>1)y+=30;t->setBounds(col*cellW,y,cellW,28);}y+=42;int ci=0;for(auto& c:choices){c->setBounds(ci++*160,y,156,52);}controlContent.setSize(cols*cellW,y+58);}
void AuroraBroadcastProcessorEditor::timerCallback(){meterDisplay.repaint();footer.setText("SR "+juce::String(processor.getSampleRate(),0)+" Hz   BLOCK "+juce::String(processor.currentBlockSize())+"   LATENCY "+juce::String(processor.getLatencySamples())+" samples   v"+config::version,juce::dontSendNotification);}
void AuroraBroadcastProcessorEditor::selectRelativePreset(int delta){auto i=(presetBox.getSelectedItemIndex()+delta+processor.getNumPrograms())%processor.getNumPrograms();presetBox.setSelectedItemIndex(i,juce::sendNotificationSync);}
void AuroraBroadcastProcessorEditor::savePreset(){juce::String error;auto name="User "+juce::Time::getCurrentTime().formatted("%Y%m%d-%H%M%S");if(!processor.presets.saveUser(name,error))juce::AlertWindow::showMessageBoxAsync(juce::MessageBoxIconType::WarningIcon,"Preset save failed",error);}
void AuroraBroadcastProcessorEditor::saveAsPreset(){fileChooser=std::make_unique<juce::FileChooser>("Export Aurora preset",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("AuroraPreset.aurorapreset"),"*.aurorapreset");fileChooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[this](const juce::FileChooser& chooser){auto f=chooser.getResult();if(f!=juce::File{}){juce::String error;if(!processor.presets.exportPreset(f,error))juce::AlertWindow::showMessageBoxAsync(juce::MessageBoxIconType::WarningIcon,"Preset export failed",error);}fileChooser.reset();});}
}
